ShineBundle\Entity\Dog:
  type: entity
  table: dog
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      unique: true
    description:
      type: text
      nullable: true
    birth:
      type: datetime
  manyToOne:
    breed:
      targetEntity: Breed
      inversedBy: dogs
      joinColumn:
        name: breed_id
        referencedColumnName: id
